- type: job
  id: HeadOfMedicalSector
  name: job-name-head-of-medical-sector
  description: job-description-head-of-medical-sector
  playTimeTracker: JobHeadOfMedicalSector
  requirements:
  - !type:RoleTimeRequirement
    role: JobMedicalSpecialist
    time: 7200
  - !type:RoleTimeRequirement
    role: JobPharmaceuticalSpecialist
    time: 10800
  - !type:DepartmentTimeRequirement
    department: MedicalService
    time: 36000
  - !type:AgeRequirement
    requiredAge: 35
  weight: 945
  icon: JobHeadOfMedicalSector
  supervisors: job-supervisors-director
  canBeAntag: true
  radioBold: true
  displayWeight: 60
  accessGroups:
  - HeadOfMedicalSector
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpAnnounceOnSpawn
      text: head-announce-on-spawn
      channels:
      - MedicalService
      includeJobName: true
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии
    - type: ShowScp096FaceDamageHud
    - type: ScpKnowledge
      knownKnowledge:
      - ScpKnowledgeTermLightContainmentZone
      - ScpKnowledgeLocationLightContainmentZone
      - ScpKnowledgeTermHeavyContainmentZone
      - ScpKnowledgeLocationHeavyContainmentZone
      - ScpKnowledgeTermAdministrativeZone
      - ScpKnowledgeTermExternalAdministrativeZone
      - ScpKnowledgeEntityScp035
      - ScpKnowledgeEntityScp049
      - ScpKnowledgeEntityScp082
      - ScpKnowledgeEntityScp096
      - ScpKnowledgeEntityScp106
      - ScpKnowledgeEntityScp131
      - ScpKnowledgeEntityScp173
      - ScpKnowledgeEntityScp247
      - ScpKnowledgeEntityScp457
      - ScpKnowledgeEntityScp939
      - ScpKnowledgeEntityScp999
      - ScpKnowledgeEntityScp079
      - ScpKnowledgeEntityScp005
      - ScpKnowledgeEntityScp012
      - ScpKnowledgeEntityScp018
      - ScpKnowledgeEntityScp101
      - ScpKnowledgeEntityScp109
      - ScpKnowledgeEntityScp124
      - ScpKnowledgeEntityScp127
      - ScpKnowledgeEntityScp2022
      - ScpKnowledgeEntityScp207
      - ScpKnowledgeEntityScp2398
      - ScpKnowledgeEntityScp261
      - ScpKnowledgeEntityScp268
      - ScpKnowledgeEntityScp330
      - ScpKnowledgeEntityScp427
      - ScpKnowledgeEntityScp500
      - ScpKnowledgeEntityScp714
      - ScpKnowledgeLocationClassDContainmentZone
      - ScpKnowledgeTermSpecialContainmentProcedures
      - ScpKnowledgeTermContainmentBreach
      - ScpKnowledgeTermContainmentRestoration
      - ScpKnowledgeTermContainmentChamber
      - ScpKnowledgeTermRegionalAdministration
      - ScpKnowledgeTermChaosInsurgency
      - ScpKnowledgeTermGlobalOccultCoalition
      - ScpKnowledgeTermPersonalArtificialIntelligence
      - ScpKnowledgeTermLegalCode
      - ScpKnowledgeTermCodeOfEthics
- type: startingGear
  id: HeadOfMedicalSectorGear
  equipment:
    head: ClothingHeadHatBeretParamedic
    eyes: ClothingEyesGlasses
    mask: ClothingMaskSterileBlack
    neck: ClothingNeckScarfCmo
    outerClothing: ClothingOuterCoatLab
    jumpsuit: ClothingUniformJumpsuitCMO
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorBrown
    back: ClothingBackpackMedical
    id: KeyCardHeadOfMedicalSector
    ears: ClothingHeadsetAltMedicalService
    belt: ClothingBeltMedicalFilled
    pocket2: HeadOfMedicalSectorPDA
  storage:
    back:
    - Flash
    - Telebaton
