- type: job
  id: ScientificServiceDirector
  name: job-name-scientific-service-director
  description: job-description-scientific-service-director
  playTimeTracker: JobScientificServiceDirector
  requirements:
  - !type:DepartmentTimeRequirement
    department: ScientificService
    time: 54000
  - !type:AgeRequirement
    requiredAge: 35
  weight: 960
  icon: JobScientificServiceDirector
  supervisors: job-supervisors-director
  canBeAntag: true
  radioBold: true
  displayWeight: 50
  accessGroups:
  - ScientificServiceDirector
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Four
    - type: ScpAnnounceOnSpawn
      text: head-announce-on-spawn
      channels:
      - ScientificService
      includeJobName: true
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud
    - type: ScpKnowledge
      knownKnowledge:
      - ScpKnowledgeTermLightContainmentZone
      - ScpKnowledgeLocationLightContainmentZone
      - ScpKnowledgeTermHeavyContainmentZone
      - ScpKnowledgeLocationHeavyContainmentZone
      - ScpKnowledgeTermAdministrativeZone
      - ScpKnowledgeTermExternalAdministrativeZone
      - ScpKnowledgeEntityScp035
      - ScpKnowledgeEntityScp049
      - ScpKnowledgeEntityScp082
      - ScpKnowledgeEntityScp096
      - ScpKnowledgeEntityScp106
      - ScpKnowledgeEntityScp131
      - ScpKnowledgeEntityScp173
      - ScpKnowledgeEntityScp247
      - ScpKnowledgeEntityScp457
      - ScpKnowledgeEntityScp939
      - ScpKnowledgeEntityScp999
      - ScpKnowledgeEntityScp079
      - ScpKnowledgeEntityScp005
      - ScpKnowledgeEntityScp012
      - ScpKnowledgeEntityScp018
      - ScpKnowledgeEntityScp101
      - ScpKnowledgeEntityScp109
      - ScpKnowledgeEntityScp124
      - ScpKnowledgeEntityScp127
      - ScpKnowledgeEntityScp2022
      - ScpKnowledgeEntityScp207
      - ScpKnowledgeEntityScp2398
      - ScpKnowledgeEntityScp261
      - ScpKnowledgeEntityScp268
      - ScpKnowledgeEntityScp330
      - ScpKnowledgeEntityScp427
      - ScpKnowledgeEntityScp500
      - ScpKnowledgeEntityScp714
- type: startingGear
  id: ScientificServiceDirectorGear
  equipment:
    eyes: ClothingEyesGlasses
    neck: ClothingNeckScarfRD
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorBrown
    back: ClothingBackpackScience
    id: KeyCardScientificServiceDirector
    ears: ClothingHeadsetAltScientificService
    pocket1: HandheldRoboAnalyzer
    pocket2: ScientificServiceDirectorPDA
  storage:
    back:
    - Flash
    - Telebaton
