- type: job
  id: LightContainmentTechnician
  name: job-name-light-containment-technician
  description: job-description-light-containment-technician
  playTimeTracker: JobLightContainmentTechnician
  startingGear: LightContainmentTechnicianGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-chief-technical-specialist
  displayWeight: 10
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: LightContainmentTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    id: EngineerPDA
    #storage:
    #back:
    #- Stuff
