- type: job
  id: PharmaceuticalSpecialist
  name: job-name-pharmaceutical-specialist
  description: job-description-pharmaceutical-specialist
  playTimeTracker: JobPharmaceuticalSpecialist
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 часов
  startingGear: PharmaceuticalSpecialistGear
  icon: JobPharmaceuticalSpecialist
  supervisors: job-supervisors-head-of-medical-sector
  displayWeight: 30
  accessGroups:
  - PharmaceuticalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии

- type: startingGear
  id: PharmaceuticalSpecialistGear
  equipment:
    id: KeyCardPharmaceuticalSpecialist
    ears: ClothingHeadsetMedicalService
    belt: ChemBag
    pocket1: HandLabeler
    eyes: ClothingEyesGlassesChemical
