using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.Scp173.UI;

[GenerateTypedNameReferences]
public sealed partial class Scp173ReagentBar : PanelContainer
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private static readonly StyleBoxFlat BloatedColor = new()
    {
        BackgroundColor = StyleNano.BloodRed,
    };

    private static readonly StyleBoxFlat NormalColor = new()
    {
        BackgroundColor = StyleNano.GoodGreenFore,
    };

    public Scp173ReagentBar()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateInfo(float current, float max, float bloatedMax)
    {
        if (current >= max)
        {
            InfoLabel.Text = _loc.GetString("scp173-reagent-bar-title", ("current", current), ("max", bloatedMax));

            ProgressBar.MaxValue = bloatedMax;
            ProgressBar.ForegroundStyleBoxOverride = BloatedColor;
        }
        else
        {
            InfoLabel.Text = _loc.GetString("scp173-reagent-bar-title", ("current", current), ("max", max));

            ProgressBar.MaxValue = max;
            ProgressBar.ForegroundStyleBoxOverride = NormalColor;
        }

        ProgressBar.Value = current;
        ProgressLabel.Text = $"{(int) (current / max * 100)}%";
    }
}
