using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Scp.Scp173.UI;

[GenerateTypedNameReferences]
public sealed partial class Scp173ReagentBar : PanelContainer
{
    public Scp173ReagentBar()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateInfo(float current, float max)
    {
        var message = new FormattedMessage();
        message.AddText(Loc.GetString("scp173-reagent-bar-title", ("current", current), ("max", max)));
        message.Pop();
        InfoLabel.SetMessage(message);

        ProgressBar.Value = current;
        ProgressBar.MaxValue = max;
        ProgressLabel.Text = $"{(int) (current / max * 100)}%";
    }
}
