using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.Fear.UI;

[GenerateTypedNameReferences]
public sealed partial class FearInfo : Control
{
    public string PhobiaNameString
    {
        set => PhobiaName.Text = Loc.GetString(value);
    }

    public string Description
    {
        set => PhobiaDescription.Text = Loc.GetString(value);
    }

    public Color? Color
    {
        set
        {
            if (value == null)
            {
                ColoredLine.Visible = false;
                return;
            }

            var panel = (StyleBoxFlat) ColoredLine.PanelOverride!;
            panel.BackgroundColor = value.Value;
        }
    }

    public FearInfo()
    {
        RobustXamlLoader.Load(this);
    }
}
