- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#FF5297"
  weight: 80
  editorHidden: true # Fire added
  roles:
    - Magistrat
    - IAA
    - Lawyer
    - NtrOfficer

- type: department # Surnise-Blueshield
  id: Blueshield
  name: department-Blueshield
  description: department-Blueshield-description
  color: "#005bfb"  # Иначе плохо видно
  roles:
    - BlueShield
  primary: false
  editorHidden: true # Fire added
  weight: 50

- type: department
  id: PlanetPrison
  sort: 0
  name: department-PlanetPrison
  description: department-PlanetPrison-description
  color: "#9f4000"
  editorHidden: true # Fire added
  roles:
  - HeadOfPrison
  - PrisonPilot
  - PrisonWorker
  - PrisonChef
  - PrisonDoctor
  - PrisonEngineer
  - PrisonGuard
  - PlanetPrisoner
