using Content.Client.Stylesheets;
using Content.Shared._Scp.SafeTime;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Scp.SafeTime;

[GenerateTypedNameReferences]
public sealed partial class SafeTimeProgressBar : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private static readonly StyleBoxFlat SafeTimeColor = new()
    {
        BackgroundColor = StyleNano.ConcerningOrangeFore,
    };

    public SafeTimeProgressBar()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Обновляет и актуализирует информацию о безопасном времени
    /// </summary>
    /// <param name="time">Все безопасное время, установленное для сущности</param>
    public void UpdateSafeTimeInfo(TimeSpan? time)
    {
        if (!time.HasValue)
        {
            Visible = false;
            return;
        }

        var timeLeft = time - _timing.CurTime;
        if (timeLeft <= TimeSpan.Zero)
        {
            Visible = false;
            return;
        }

        Visible = true;

        var timeLeftString = SafeTimeSystem.GetTimeLeft(timeLeft.Value);
        InfoLabel.Text = _loc.GetString("safe-time-title", ("time", timeLeftString));

        ProgressBar.MaxValue = (int) time.Value.TotalSeconds;
        ProgressBar.ForegroundStyleBoxOverride = SafeTimeColor;

        var elapsed = (int) (time.Value.TotalSeconds - timeLeft.Value.TotalSeconds);
        ProgressBar.Value = elapsed;
        ProgressLabel.Text = $"{(int) (elapsed / time.Value.TotalSeconds * 100)}%";
    }
}
