- type: job
  id: ProductionSpecialist
  name: job-name-production-specialist
  description: job-description-production-specialist
  playTimeTracker: JobProductionSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: ScientificService
    time: 10800
  - !type:DepartmentTimeRequirement
    department: EngineeringTechnicalService
    time: 10800
  - !type:AgeRequirement
    requiredAge: 25
  - !type:AgeRequirement
    requiredAge: 75
    inverted: true
  icon: JobProductionSpecialist
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 10
  weight: 790
  accessGroups:
  - ProductionSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud
    - type: ScpKnowledge
      knownKnowledge:
      - ScpKnowledgeTermLightContainmentZone
      - ScpKnowledgeLocationLightContainmentZone
      - ScpKnowledgeTermHeavyContainmentZone
      - ScpKnowledgeLocationHeavyContainmentZone
      - ScpKnowledgeTermAdministrativeZone
      - ScpKnowledgeTermExternalAdministrativeZone
      - ScpKnowledgeEntityScp035
      - ScpKnowledgeEntityScp049
      - ScpKnowledgeEntityScp082
      - ScpKnowledgeEntityScp096
      - ScpKnowledgeEntityScp106
      - ScpKnowledgeEntityScp131
      - ScpKnowledgeEntityScp173
      - ScpKnowledgeEntityScp247
      - ScpKnowledgeEntityScp457
      - ScpKnowledgeEntityScp939
      - ScpKnowledgeEntityScp999
      - ScpKnowledgeEntityScp079
      - ScpKnowledgeEntityScp005
      - ScpKnowledgeEntityScp012
      - ScpKnowledgeEntityScp018
      - ScpKnowledgeEntityScp101
      - ScpKnowledgeEntityScp109
      - ScpKnowledgeEntityScp124
      - ScpKnowledgeEntityScp127
      - ScpKnowledgeEntityScp2022
      - ScpKnowledgeEntityScp207
      - ScpKnowledgeEntityScp2398
      - ScpKnowledgeEntityScp261
      - ScpKnowledgeEntityScp268
      - ScpKnowledgeEntityScp330
      - ScpKnowledgeEntityScp427
      - ScpKnowledgeEntityScp500
      - ScpKnowledgeEntityScp714
- type: startingGear
  id: ProductionSpecialistGear
  equipment:
    head: ClothingHeadHatCorpsoft
    neck: ClothingNeckTieSci
    jumpsuit: ClothingUniformJumpsuitRoboticist
    outerClothing: ClothingOuterCoatRobo
    shoes: ClothingShoesColorWhite
    back: ClothingBackpackScience
    id: KeyCardProductionSpecialist
    ears: ClothingHeadsetScientificService
    pocket2: ScpResearchPDA
