- type: job
  id: RoboticsSpecialist
  name: job-name-robotics-specialist
  description: job-description-robotics-specialist
  playTimeTracker: JobRoboticsSpecialist
  startingGear: RoboticsSpecialistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-lead-researcher
  displayWeight: 10
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticsSpecialistGear
  equipment:
    ears: ClothingHeadsetScience
    id: SciencePDA
    #storage:
    #back:
    #- Stuff
