- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 #5 hrs # Sunrise-RoleTime
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  displayWeight: 0 # Sunrise-Edit
  access:
  - Research # FireStation Edit
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: SecurityCadetGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    gloves: ClothingHandsGlovesSecurity
    jumpsuit: ClothingUniformSecurity2
    shoes: ClothingShoesBootsSecurityGuard
    outerClothing: ClothingOuterArmorSecurity
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    pocket1: HyperLinkBookCorporateLaw # Sunrise-edit
  storage:
    back:
    - Flash
