- type: loadoutEffectGroup
  id: MasterSecurity
  effects:
  # Fire edit start
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:DepartmentTimeRequirement
      department: HeavyContainmentSecurityService
      time: 36000 #10 hrs
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:DepartmentTimeRequirement
      department: ExternalAdministrativeZoneSecurityService
      time: 36000 #10 hrs
  # Fire edit end

- type: loadout
  id: SecurityBodycam
  startingGear: SecurityBodycam

- type: startingGear
  id: SecurityBodycam
  storage:
    back:
    - HandheldCamera

- type: loadout
  id: SecurityPepperspray
  startingGear: PeppersprayBlue

- type: startingGear
  id: PeppersprayBlue
  storage:
    back:
    - PepperSprayBottleBlue

- type: loadout
  id: SecurityWhistle
  startingGear: SecurityWhistle

- type: startingGear
  id: SecurityWhistle
  storage:
    back:
    - SecurityWhistle

- type: loadout
  id: SecurityRadioHandheld
  startingGear: SecurityRadioHandheld

- type: startingGear
  id: SecurityRadioHandheld
  storage:
    back:
    - RadioHandheldSecurity

- type: loadout
  id: SecurityTourniquet
  startingGear: SecurityTourniquet

- type: startingGear
  id: SecurityTourniquet
  storage:
    back:
    - Tourniquet

- type: loadout
  id: SecurityGrenadeStinger
  startingGear: SecurityGrenadeStinger

- type: startingGear
  id: SecurityGrenadeStinger
  storage:
    belt:
    - GrenadeStinger

- type: loadout
  id: SecurityClusterBangFull
  startingGear: SecurityClusterBangFull

- type: startingGear
  id: SecurityClusterBangFull
  storage:
    belt:
    - ClusterBangFull

- type: loadout
  id: SecurityTearGasGrenade
  startingGear: SecurityTearGasGrenade

- type: startingGear
  id: SecurityTearGasGrenade
  storage:
    belt:
    - TearGasGrenade

- type: loadout
  id: SecurityWeaponMeleeNeedle
  startingGear: SecurityWeaponMeleeNeedle

- type: startingGear
  id: SecurityWeaponMeleeNeedle
  storage:
    back:
    - WeaponMeleeNeedle

# - type: loadout #Fire-Station
#   id: SecurityHoloprojector
#   startingGear: SecurityHoloprojector

# - type: startingGear #Fire-Station
#   id: SecurityHoloprojector
#   storage:
#     back:
#     - HoloprojectorSecurity

- type: loadout
  id: GlockBox
  startingGear: GlockBox

- type: startingGear
  id: GlockBox
  storage:
    back:
    - GlockBox

- type: loadout
  id: ACP14Box
  startingGear: ACP14Box
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterSecurity

- type: startingGear
  id: ACP14Box
  storage:
    back:
    - ACP14Box

- type: loadout
  id: WeaponEnergyGunPistolSecurity
  startingGear: WeaponEnergyGunPistolSecurity

- type: startingGear
  id: WeaponEnergyGunPistolSecurity
  storage:
    back:
    - WeaponEnergyGunPistolSecurity

- type: loadout
  id: WeaponDisabler
  startingGear: WeaponDisabler

- type: startingGear
  id: WeaponDisabler
  storage:
    back:
    - WeaponDisabler

- type: loadout
  id: WeaponTaser
  startingGear: WeaponTaser

- type: startingGear
  id: WeaponTaser
  storage:
    back:
    - WeaponTaser
