- type: job # TODO: Узнать че за хуй и сделать норм
  id: APAIBAgent
  name: job-name-apaib-agent
  description: job-description-apaib-agent
  playTimeTracker: JobAPAIBAgent
  weight: 10
  startingGear: APAIBAgentGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-director
  canBeAntag: true
  radioBold: true
  displayWeight: 40
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: APAIBAgentGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    #    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
