- type: job
  id: InternalSecurityOperative
  name: job-name-internal-security-operative
  description: job-description-internal-security-operative
  playTimeTracker: JobInternalSecurityOperative
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 90000 # 25 часов
  startingGear: InternalSecurityOperativeGear
  icon: JobInternalSecurityOperative
  supervisors: job-supervisors-regional-administration
  canBeAntag: false
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Cargo
  - Medical
  - BlueShield
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [MindShieldImplant]

- type: entity
  parent: BlueShieldPDA
  id: ISOPDA
  name: Internal Security Operative PDA
  description: Your safety inside the foundation is in the hands of this guy, but can you trust him?
  components:
  - type: Pda
    id: ISOIDCard

- type: entity
  parent: IDCardStandard
  id: ISOIDCard
  name: Internal Security Operative ID card
  components:
  - type: Sprite
    sprite: _Scp/Objects/Misc/id_cards.rsi
    layers:
    - state: silver
    - state: id-iso
  - type: PresetIdCard
    job: InternalSecurityOperative

- type: startingGear
  id: InternalSecurityOperativeGear
  equipment:
    shoes: ClothingShoesBootsBlueShieldFilled
    eyes: ClothingEyesGlassesBlueShield
    head: ClothingHeadHatBeretBlueShield
    outerClothing: ClothingOuterArmorBlueShield
    id: ISOPDA
    ears: ClothingHeadsetAltInternalSecurity
    belt: ClothingBeltBlueShieldWebbingFilled
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - HandheldCrewMonitor
