- type: job
  id: MentalControlOfficer
  name: job-name-mental-control-officer
  description: job-description-mental-control-officer
  playTimeTracker: JobMentalControlOfficer
  startingGear: MentalControlOfficerGear
  icon: JobMentalControlOfficer
  supervisors: job-supervisors-regional-administration
  canBeAntag: false
  displayWeight: 40
  setPreference: false # TODO: После добавления вайт-листа убрать
  access:
  - Command
  - Service
  - Brig
  - Maintenance
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Fear
      timeToDecreaseFearLevel: 120
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 2
        Fear: 5
        Terror: 10

- type: startingGear
  id: MentalControlOfficerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetAltInternalSecurity
    pocket2: HyperLinkBookCorporateLaw
  inhand:
  - BriefcaseIAAFilled
