using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.FreeScp;

[GenerateTypedNameReferences]
public sealed partial class FreeScpTransferWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public FreeScpTransferWindow(string scpName)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        BodyLabel.Text = _loc.GetString("free-scp-transfer-window-body", ("scp", scpName));
        TransferNowButton.Text = _loc.GetString("free-scp-transfer-window-now");
        WaitButton.Text = _loc.GetString("free-scp-transfer-window-wait");
        DeclineButton.Text = _loc.GetString("free-scp-transfer-window-decline");
    }
}
