using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.FreeScp;

[GenerateTypedNameReferences]
public sealed partial class FreeScpPollWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public FreeScpPollWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        BodyLabel.Text = _loc.GetString("free-scp-poll-window-body");
        AcceptButton.Text = _loc.GetString("free-scp-poll-window-accept");
        DeclineButton.Text = _loc.GetString("free-scp-poll-window-decline");
    }
}
