- type: entity
  parent: ClothingShoesBaseButcherable
  id: ClothingShoesBootsSecurityGuard
  name: security shoes
  description: Gay's shoes.
  suffix: SCP14
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Shoes/security_guard.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Shoes/security_guard.rsi

- type: entity
  parent: ClothingShoesBaseButcherable
  id: ClothingShoesBootsWinterSecurityGuard
  name: winter security shoes
  description: Gay's shoes.
  suffix: SCP14
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Shoes/winter_security_guard.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Shoes/winter_security_guard.rsi
