- type: job
  id: SeniorContainmentGuard
  name: job-name-senior-containment-guard
  description: job-description-senior-containment-guard
  playTimeTracker: JobSeniorContainmentGuard
  startingGear: SeniorContainmentGuardGear
  icon: "JobIconSeniorContainmentGuard"
  supervisors: job-supervisors-head-of-containment
  access:
  - Maintenance

- type: startingGear
  id: SeniorContainmentGuardGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  