- type: job
  id: ContainmentSpecialist
  name: job-name-containment-specialist
  description: job-description-containment-specialist
  playTimeTracker: JobContainmentSpecialist
  startingGear: ContainmentSpecialistGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-heavy-containment-security-supervisor
  canBeAntag: false
  displayWeight: 10
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ContainmentSecuritySpecialistGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22
