- type: job
  id: FieldMedicalSpecialist
  name: job-name-field-medical-specialist
  description: job-description-field-medical-specialist
  playTimeTracker: JobFieldMedicalSpecialist
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 часов
  startingGear: FieldMedicalSpecialistGear
  icon: JobFieldMedicalSpecialist
  supervisors: job-supervisors-heavy-containment-zone-commandant
  canBeAntag: false
  displayWeight: 15
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  - Research
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии

- type: startingGear
  id: FieldMedicalSpecialistGear
  equipment:
    outerClothing: ClothingOuterCoatLabSecurityMedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesLatex
    eyes: ClothingEyesHudMedSec
    head: ClothingHeadHatBeretSecurityMedic
    id: BrigmedicPDA
    ears: ClothingHeadsetFieldMedicalSpecialist
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash
