- type: job
  id: HeavyContainmentZoneCommandant
  name: job-name-heavy-containment-zone-commandant
  description: job-description-heavy-containment-zone-commandant
  playTimeTracker: JobHeavyContainmentZoneCommandant
  startingGear: HeavyContainmentZoneCommandantGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-security-commander
  canBeAntag: false
  displayWeight: 70  # Sunrise
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  - Armory
  #  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: HeavyContainmentZoneCommandantGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - Flash
#    - MagazineGlock22
