- type: job
  id: JuniorHeavyContainmentZoneOfficer
  name: job-name-junior-external-administrative-zone-officer
  description: job-description-junior-external-administrative-zone-officer
  playTimeTracker: JobJuniorHeavyContainmentZoneOfficer
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 часов
  startingGear: JuniorHeavyContainmentZoneOfficerGear
  icon: JobJuniorHeavyContainmentZoneOfficer
  supervisors: job-supervisors-heavy-containment-zone-commandant
  canBeAntag: false
  displayWeight: 0
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: JuniorHeavyContainmentZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    id: SecurityCadetPDA
    ears: ClothingHeadsetHeavyContainmentSecurityService
    pocket1: HyperLinkBookCorporateLaw
  storage:
    back:
    - Flash
