- type: job
  id: SeniorHeavyContainmentZoneOfficer
  name: job-name-senior-heavy-containment-zone-officer
  description: job-description-senior-heavy-containment-zone-officer
  playTimeTracker: JobSeniorHeavyContainmentZoneOfficer
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 часов
  startingGear: SeniorHeavyContainmentZoneOfficerGear
  icon: JobSeniorHeavyContainmentZoneOfficer
  supervisors: job-supervisors-heavy-containment-zone-commandant
  canBeAntag: false
  displayWeight: 10
  accessGroups:
  - SecurityJobCommon
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: SeniorHeavyContainmentZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: KeyCardSeniorHeavyContainmentZoneOfficer
    ears: ClothingHeadsetHeavyContainmentSecurityService
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
    pocket2: ScpSecurityPDA
  storage:
    back:
    - Flash
