- type: job
  id: SeniorHeavyContainmentZoneOfficer
  name: job-name-senior-heavy-containment-zone-officer
  description: job-description-senior-heavy-containment-zone-officer
  playTimeTracker: JobSeniorHeavyContainmentZoneOfficer
  startingGear: SeniorHeavyContainmentZoneOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-heavy-containment-security-supervisor
  canBeAntag: false
  displayWeight: 10
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorHeavyContainmentZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22
