- type: job
  id: SecuritySpecialist
  name: job-name-security-specialist
  description: job-description-security-specialist
  playTimeTracker: JobSecuritySpecialist
  startingGear: SecuritySpecialistGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-security-specialist
  canBeAntag: false
  displayWeight: 10
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecuritySpecialistGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22
