- type: entity
  parent: ClothingBeltSecurityWebbing
  id: ScpClothingBeltSecurityWebbing
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Belt/security_webbing.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Belt/security_webbing.rsi
