using Content.Client.Pinpointer.UI;
using Content.Shared.Pinpointer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using System.Numerics;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NavigatorUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public NavMapControl? NavMap;
    private EntityUid? _owner;
    private readonly List<StationMapBeaconControl> _buttons = new();

    public NavigatorUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Setup(EntityUid? owner)
    {
        _owner = owner;
        NavMap = new NavMapControl();
        NavMap.Owner = owner;
        NavMap.HorizontalExpand = true;
        NavMap.VerticalExpand = true;

        NavMapContainer.AddChild(NavMap);

        FilterBar.OnTextChanged += (bar) => OnFilterChanged(bar.Text);
    }

    public void UpdateState(EntityUid? mapUid, string stationName)
    {
        StationNameLabel.Text = stationName;

        if (NavMap != null && mapUid != null)
        {
            NavMap.MapUid = mapUid;
        }

        // Track owner position on the map
        UpdateOwnerPosition();

        UpdateBeaconList(mapUid);
    }

    private void UpdateOwnerPosition()
    {
        if (NavMap == null || _owner == null || !_entManager.EntityExists(_owner.Value))
            return;

        var transformSystem = _entManager.System<SharedTransformSystem>();

        var ownerCoords = transformSystem.GetMapCoordinates(_owner.Value);
        var ownerEntityCoords = new EntityCoordinates(_owner.Value, Vector2.Zero);

        // Clear previous owner tracking
        NavMap.TrackedCoordinates.Clear();

        // Add owner position as a tracked coordinate
        NavMap.TrackedCoordinates[ownerEntityCoords] = (true, Color.Red);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Periodically update owner position
        UpdateOwnerPosition();
    }

    public void OnFilterChanged(string newFilter)
    {
        foreach (var button in _buttons)
        {
            button.Visible = string.IsNullOrEmpty(newFilter) || (
                !string.IsNullOrEmpty(button.Label) &&
                button.Label.Contains(newFilter, StringComparison.OrdinalIgnoreCase)
            );
        }
    }

    public void UpdateBeaconList(EntityUid? mapUid)
    {
        BeaconButtons.Children.Clear();
        _buttons.Clear();

        if (!mapUid.HasValue)
            return;

        if (!_entManager.TryGetComponent<NavMapComponent>(mapUid, out var navMap))
            return;

        foreach (var beacon in navMap.Beacons.Values)
        {
            var button = new StationMapBeaconControl(mapUid.Value, beacon);

            button.OnPressed += coords => NavMap?.CenterToCoordinates(coords);

            _buttons.Add(button);
        }

        _buttons.Sort();

        foreach (var button in _buttons)
            BeaconButtons.AddChild(button);
    }
}
