#- type: entity
#  id: BaseStationMogGroups
#  abstract: true
#  components:
#  - type: StationMogGroups
#    allowedGroups:
#    - SpetznazDog

- type: entity
  id: ScpComplexGoal
  abstract: true
  components:
  - type: StationGoal
    goals:
    - Scp1
    - Scp2
    - Scp3
    - Scp4
    - Scp5
    - Scp6
    - Scp7
    - Scp8

- type: entity
  id: BaseStationRegionalAdministration
  abstract: true
  components:
  - type: StationCentComm
    station: RegionalAdministrationBase
    shuttleWhitelist:
      components:
      - CentCommShuttle
      - ErtShuttle

- type: entity
  id: BaseComplexTransitHub
  abstract: true
  components:
  - type: StationTransitHub
    map: /Maps/_Scp/regional_administration_base.yml
    biomes:
    - Snow
