- type: job
  id: Governor
  name: job-name-Governor
  description: job-description-Governor
  playTimeTracker: JobGovernor
  startingGear: GovernorGear
  icon: "JobIconGovernor"
  supervisors: job-supervisors-head-of-containment
  access:
  - Maintenance

- type: startingGear
  id: GovernorGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
