- type: job
  id: ExternalAdministrativeZoneOfficer
  name: job-name-external-administrative-zone-officer
  description: job-description-external-administrative-zone-officer
  playTimeTracker: JobExternalAdministrativeZoneOfficer
  startingGear: ExternalAdministrativeZoneOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 10
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ExternalAdministrativeZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    eyes: ClothingEyesGlassesSecurityGuard
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22
