- type: job
  id: ExternalAdministrativeZoneCommandant
  name: job-name-external-administrative-zone-commandant
  description: job-description-external-administrative-zone-commandant
  playTimeTracker: JobExternalAdministrativeZoneCommandant
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 90000 # 25 часов
  startingGear: ExternalAdministrativeZoneCommandantGear
  icon: JobExternalAdministrativeZoneCommandant
  supervisors: job-supervisors-security-commander
  canBeAntag: false
  displayWeight: 70
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  - Armory
  #  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Fear
      timeToDecreaseFearLevel: 120
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 2
        Fear: 5
        Terror: 10

- type: startingGear
  id: ExternalAdministrativeZoneCommandantGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetAltExternalAdministrativeZoneSecurityService
  storage:
    back:
    - Flash
#    - MagazineGlock22
