- type: job
  id: JuniorExternalAdministrativeZoneOfficer
  name: job-name-junior-external-administrative-zone-officer
  description: job-description-junior-external-administrative-zone-officer
  playTimeTracker: JobJuniorExternalAdministrativeZoneOfficer
  startingGear: JuniorExternalAdministrativeZoneOfficerGear
  icon: JobJuniorExternalAdministrativeZoneOfficer
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 0
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: JuniorExternalAdministrativeZoneOfficer
  equipment:
    mask: ClothingMaskSecurityBandBlack
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    pocket1: HyperLinkBookCorporateLaw
  storage:
    back:
    - Flash
