- type: job
  id: JuniorExternalAdministrativeZoneOfficer
  name: job-name-junior-external-administrative-zone-officer
  description: job-description-junior-external-administrative-zone-officer
  playTimeTracker: JobJuniorExternalAdministrativeZoneOfficer
  startingGear: JuniorExternalAdministrativeZoneOfficerGear
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 18000 # 5 часов
  icon: JobJuniorExternalAdministrativeZoneOfficer
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 0
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  #  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: JuniorExternalAdministrativeZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    id: SecurityCadetPDA
    ears: ClothingHeadsetExternalAdministrativeZoneSecurityService
    pocket1: HyperLinkBookCorporateLaw
  storage:
    back:
    - Flash
