- type: job
  id: SeniorExternalAdministrativeZoneOfficer
  name: job-name-senior-external-administrative-zone-officer
  description: job-description-senior-external-administrative-zone-officer
  playTimeTracker: JobSeniorExternalAdministrativeZoneOfficer
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 часов
  startingGear: SeniorExternalAdministrativeZoneOfficerGear
  icon: JobSeniorExternalAdministrativeZoneOfficer
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 60
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorExternalAdministrativeZoneOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    id: SeniorOfficerPDA
    ears: ClothingHeadsetExternalAdministrativeZoneSecurityService
  storage:
    back:
    - WeaponDisablerSMG
