- type: job
  id: SeniorExternalAdministrativeZoneOfficer
  name: job-name-senior-external-administrative-zone-officer
  description: job-description-senior-external-administrative-zone-officer
  playTimeTracker: JobSeniorExternalAdministrativeZoneOfficer
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 часов
  startingGear: SeniorExternalAdministrativeZoneOfficerGear
  icon: JobSeniorExternalAdministrativeZoneOfficer
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 60
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: SeniorExternalAdministrativeZoneOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    id: SeniorOfficerPDA
    ears: ClothingHeadsetExternalAdministrativeZoneSecurityService
  storage:
    back:
    - WeaponDisablerSMG
