using Content.Client._Scp.Stylesheets.Palette;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";

    // Fire edit start
    public static readonly string NormalBgColor = ScpPalettes.PanelDarker.ToHex();
    public static readonly string HoverColor = ScpPalettes.LightGray.ToHex();
    // Fire edit end

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = ScpPalettes.PanelDarker, // Fire edit
    };

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

    }
}
