using Content.Client._Scp.Stylesheets.Palette;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaSettingsButton : ContainerButton
{
    public const string StylePropertyFgColor = "foregroundColor";
    public const string StylePropertyBgColor = "backgroundColor";

    // Fire edit start
    public static readonly string NormalBgColor = ScpPalettes.PanelDarker.ToHex();
    public static readonly string HoverColor = ScpPalettes.LightGray.ToHex();
    public static readonly string PressedColor = ScpPalettes.BloodRedDarker.ToHex();
    public static readonly string DisabledFgColor = ScpPalettes.LightGray.ToHex();
    public static readonly string EnabledFgColor = ScpPalettes.SCPWhite.ToHex();
    // Fire edit end

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = ScpPalettes.PanelDark, // Fire edit
    };

    public string? Text
    {
        get => OptionName.Text;
        set => OptionName.Text = value;
    }
    public string? Description
    {
        get => OptionDescription.Text;
        set => OptionDescription.Text = value;
    }

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public Color? ForegroundColor
    {
        get => OptionName.FontColorOverride;

        set
        {
            OptionName.FontColorOverride = value;
            OptionDescription.FontColorOverride = value;
        }
    }

    public PdaSettingsButton()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

        if (TryGetStyleProperty<Color>(StylePropertyFgColor, out var fgColor))
            ForegroundColor = fgColor;

    }
}
