- type: job
  id: SeniorInternalSecurityAgent
  name: job-name-senior-internal-security-agent
  description: job-description-senior-internal-security-agent
  playTimeTracker: JobSeniorInternalSecurityAgent
  startingGear: SeniorInternalSecurityAgentGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-external-internal-security-supervisor
  canBeAntag: false
  displayWeight: 60
  access:
  - Research
  - Kitchen
  - Hydroponics
  - Janitor
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorInternalSecurityAgentGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - WeaponDisablerSMG
