using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.UI;

[GenerateTypedNameReferences]
public sealed partial class ColoredInfo : Control
{
    public string NameString
    {
        set => Name.Text = Loc.GetString(value);
    }

    public string DescriptionString
    {
        set => Description.Text = Loc.GetString(value);
    }

    public Color? Color
    {
        set
        {
            if (value == null)
            {
                ColoredLine.Visible = false;
                return;
            }

            if (ColoredLine.PanelOverride is not StyleBoxFlat panel)
            {
                ColoredLine.Visible = false;
                return;
            }

            panel.BackgroundColor = value.Value;
            ColoredLine.Visible = true;
        }
    }

    public ColoredInfo()
    {
        RobustXamlLoader.Load(this);
    }
}
