using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.UI;

[GenerateTypedNameReferences]
public sealed partial class CompatibilityModeActiveWarningWindow : FancyWindow
{
    public CompatibilityModeActiveWarningWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
