using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Scp.Other.ShowMessageOnSpawn;

[GenerateTypedNameReferences]
public sealed partial class ShowMessageOnSpawnWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public ShowMessageOnSpawnWindow(LocId message)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        BodyLabel.Text = _loc.GetString(message);
    }
}
