- type: job
  id: LogisticsOfficer
  name: job-name-logistics-officer
  description: job-description-logistics-officer
  playTimeTracker: JobLogisticsOfficer
  startingGear: LogisticsOfficerGear
  icon: JobLogisticsOfficer
  supervisors: job-supervisors-senior-logistics-officer
  displayWeight: 0
  accessGroups:
  - LogisticsOfficer
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: One

- type: startingGear
  id: LogisticsOfficerGear
  equipment:
    id: KeyCardLogisticsOfficer
    ears: ClothingHeadsetLogistics
    pocket1: AppraisalTool
