- type: job
  id: JudicialInspector
  name: job-name-judicial-inspector
  description: job-description-judicial-inspector
  playTimeTracker: JobJudicialInspector
  startingGear: JudicialInspectorGear
  icon: JobJudicialInspector
  supervisors: job-supervisors-regional-administration
  canBeAntag: false
  radioBold: true
  displayWeight: 75
  access:
  - Magistrat
  - Bar
  - Kitchen
  - Hydroponics
  - Janitor
  - Theatre
  - Chapel
  - Lawyer
  - Brig
  - Security
  - Medical
  - Research
  - Engineering
  - Cargo
  - Salvage
  - Command
  - Hydroponics
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: JudicialInspectorGear
  equipment:
    jumpsuit: MagistratUniformSuit
    back: ClothingBackpack
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterRobesJudge
    id: MagistratPDA
    ears: ClothingHeadsetMagistrate
    head: ClothingHeadHatPwig
  storage:
    back:
    - RubberStampMagistrat
    - ClothingNeckLawyerbadge
    - GavelHammer
    - GavelBlock
