- type: job
  id: ClassDCook
  name: job-name-class-d-cook
  description: job-description-class-d-cook
  playTimeTracker: JobClassDCook
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 час
  startingGear: ClassDCookGear
  icon: JobClassDCook
  supervisors: job-supervisors-security-and-research
  access:
  - ClassDCanteen
  alwaysUseSpawner: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: ClassDAppearance
    - type: EmployeeClass
      class: D

- type: startingGear
  id: ClassDCookGear
  equipment:
    head: ClothingHeadHatChef
    jumpsuit: ClothingUniformClassD
    outerClothing: ClothingOuterApronChef
    belt: ClothingBeltChefFilled
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesClassD
    id: KeyCardClassDCock
