# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys

- type: gameMapPool
  id: SunriseMapPool
  maps: # Fire edit - все санрайзовские карты удалены в качестве оптимизации использования RAM
  - Empty
