# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys
# ВСЕ КАРТЫ ДОЛЖНЫ ИМЕТЬ SMESExtended ВМЕСТО БАЗОВОГО SMESBasic!

- type: gameMapPool
  id: SunriseMapPool
  maps: # Fire edit - все санрайзовские карты удалены в качестве оптимизации использования RAM
  - Empty
