- type: job
  id: SanitationTechnician
  name: job-name-sanitation-technician
  description: job-description-sanitation-technician
  playTimeTracker: JobSanitationTechnician
  startingGear: SanitationTechnicianGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-service-administrator
  access:
  - Service
  - Janitor
  - Maintenance

- type: startingGear
  id: SanitationTechnicianGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
    #storage:
    #back:
    #- Stuff
