- type: job
  id: ServiceAdministrator
  name: job-name-service-administrator
  description: job-description-service-administrator
  playTimeTracker: JobServiceAdministrator
  startingGear: ServiceAdministratorGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-personnel-officer
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: ServiceAdministratorGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
    #storage:
    #back:
    #- Stuff
