- type: job
  id: EthicsCommitteeRepresentative
  name: job-name-ethics-committee-representative
  description: job-description-ethics-committee-representative
  playTimeTracker: JobEthicsCommitteeRepresentative
  requirements:
  - !type:DiscordRoleRequirement
  - !type:AgeRequirement
    requiredAge: 32
  weight: 860
  icon: JobEthicsCommitteeRepresentative
  supervisors: job-supervisors-ethics-committee
  canBeAntag: true
  radioBold: true
  displayWeight: 50
  accessGroups:
  - EthicsCommittee
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: B
    - type: AccessLevel
      level: Four
    - type: ScpKnowledge
      knownKnowledge:
      - ScpKnowledgeTermLightContainmentZone
      - ScpKnowledgeLocationLightContainmentZone
      - ScpKnowledgeTermHeavyContainmentZone
      - ScpKnowledgeLocationHeavyContainmentZone
      - ScpKnowledgeTermAdministrativeZone
      - ScpKnowledgeTermExternalAdministrativeZone
      - ScpKnowledgeEntityScp035
      - ScpKnowledgeEntityScp049
      - ScpKnowledgeEntityScp082
      - ScpKnowledgeEntityScp096
      - ScpKnowledgeEntityScp106
      - ScpKnowledgeEntityScp131
      - ScpKnowledgeEntityScp173
      - ScpKnowledgeEntityScp247
      - ScpKnowledgeEntityScp457
      - ScpKnowledgeEntityScp939
      - ScpKnowledgeEntityScp999
      - ScpKnowledgeEntityScp079
      - ScpKnowledgeEntityScp005
      - ScpKnowledgeEntityScp012
      - ScpKnowledgeEntityScp018
      - ScpKnowledgeEntityScp101
      - ScpKnowledgeEntityScp109
      - ScpKnowledgeEntityScp124
      - ScpKnowledgeEntityScp127
      - ScpKnowledgeEntityScp2022
      - ScpKnowledgeEntityScp207
      - ScpKnowledgeEntityScp2398
      - ScpKnowledgeEntityScp261
      - ScpKnowledgeEntityScp268
      - ScpKnowledgeEntityScp330
      - ScpKnowledgeEntityScp427
      - ScpKnowledgeEntityScp500
      - ScpKnowledgeEntityScp714
      - ScpKnowledgeLocationClassDContainmentZone
      - ScpKnowledgeTermSpecialContainmentProcedures
      - ScpKnowledgeTermContainmentBreach
      - ScpKnowledgeTermContainmentRestoration
      - ScpKnowledgeTermContainmentChamber
      - ScpKnowledgeTermRegionalAdministration
      - ScpKnowledgeTermChaosInsurgency
      - ScpKnowledgeTermGlobalOccultCoalition
      - ScpKnowledgeTermPersonalArtificialIntelligence
      - ScpKnowledgeTermLegalCode
      - ScpKnowledgeTermCodeOfEthics
- type: startingGear
  id: EthicsCommitteeRepresentativeGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesSunGlassesHudSkill
    head: ClothingHeadHatCapEthicsCommittee
    id: KeyCardEthicsCommitteePass
    ears: ClothingHeadsetAltEthicsCommittee
    jumpsuit: ClothingUniformJumpsuitWithWhiteShirt
    back: ClothingBackpackSatchelLeatherEthicsCommitteeFilled
    pocket2: BaseFoundationPDA
